# Konstanty
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1000
FPS = 60

SHAKE_INTENSITY = 1  # Konstantní intenzita otřesů


ASTEROID_SPAWN_DELAY = 200

ASTEROID_SPEED = 25
CHARACTER_SPEED = 5
RANDOM_MIN = 0.8
RANDOM_MAX = 2.5

INVINCIBILITY = 1

DORAZ = 13
ROZMEZI_Y = SCREEN_HEIGHT//DORAZ
ROZMEZI_X = SCREEN_HEIGHT//DORAZ
